### ISSUE TITLE
Creating Databases fails (Mysql)

### ISSUE THREAD

**Issue by snitchashor** [paxswill/evesrp#91]
When i try to create the db schema some of them are created and then the script fails
`sqlalchemy.exc.InvalidRequestError: Naming convention including %(constraint_name)s token requires that constraint is explicitly named.`

EVE-SRP 0.12.0 sqlalchemy 1.0.12

Before I had to downgrade flask migrate to 1.60 to get to this point. Would it be possible to get the Database structure as an sql file? if the evesso tables were included that would be nice.

Thanks

**Comment by paxswill** [comment]
That's odd, which specific version of MySQL and which storage engine are you using?

**Comment by paxswill** [comment]
Nevermind, I was able to reproduce and fix the problem. v0.12.1 should fix the problem.

**Comment by paxswill** [comment]
And it was actually d2066bee that fixed it.

**Comment by paxswill** [comment]
Also, Flask-Migrate was updated as well, so you shouldn't need to do that either.

**Comment by snitchashor** [comment]
Thanks. I'll give it a try, but for now I just switched to postgresql and it worked right away. I had to do a few minor fixes to the js part to get the sorting in tables to work but now 0.12 looks good.
Theres one minor issue, maybe because im running it evesso only but when someone logs in without any permissions ot results in a 500 page instead of a meaningful message but nothing urgent.

**Comment by paxswill** [comment]
Re the sorting. Yeah, I probably broke it in the last week or two when I was fixing a couple of other issues with the JS on the listing page.

On the 500, that's totally not intended and probably not due to just running it with SSO. I'll look into that later today if I can.
