### ISSUE TITLE
zkillmails also use ESI format now, so parsing needs to be adapted

### ISSUE THREAD

**Issue by kitsunet** [paxswill/evesrp#97]
Basically zkillmails need to use the same fields as the ESI killmails now, so the whole code handling ESI can be copied over to zkill (or externalised). I can provide a PR (I have it running) but I am not exactly used to python so might not be super beautiful :D 

Just let me know...

**Comment by paxswill** [comment]
Sorry for the delay in responding, it took a little bit to be able to sit down to fix it. v0.10.12 should have zKillboard support working again.
